---
 - name: installing pre-requisites
   apt: 
     name: 
       - python3
       - python3-pip
     state: present

 - name: Install docker file
   apt: 
     name: docker.io
     state: latest
     update_cache: yes
   register: docker

 - name: installing docker.py
   pip: 
     name: docker.py
     state: latest
   when: docker.changed

# tasks file for roles/ubuntu_docker